// src/config/environmentConfig.js
export const environmentConfig = [
  {
    id: "zooenterence",
    name: "Zoo Entrance",
    model: "/assets/entrance.glb",
    position: [6, 0.5, 31.5],
    rotation: [0, 0, 0],
    scale: [3, 3, 3],
  },
  {
    id: "fountain",
    name: "Fountain",
    model: "/assets/fountain.glb",
    position: [5, -0.5, 2],
    rotation: [0, 0, 0],
    scale: 1.5,
  },
  // {
  //   id: "rhinobg",
  //   name: "Rhinobg",
  //   model: "/assets/rhinobg.glb",
  //   position: [33, 0.5, 12],
  //   rotation: [0, Math.PI, 0],
  //   scale: 0.5,
  // },
  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [-17, 2.5, 31],
    rotation: [0, Math.PI, 0],
    scale: [5.3, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [30, 2.5, 31],
    rotation: [0, Math.PI, 0],
    scale: [5, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [-30, 2.5, 13],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [-30, 2.5, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [-12, 2.5, -40.5],
    rotation: [0, Math.PI, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [24, 2.5, -40.5],
    rotation: [0, Math.PI, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [42, 2.5, -25],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier",
    name: "Barrier",
    model: "/assets/barrier.glb",
    position: [42, 2.5, 12],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7.5, 3, 2],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-15, 0.1, 29.5],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-15, 0.1, 13],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-15, 0.1, -3],
    rotation: [0, -Math.PI / 2, 0],
    scale: [95, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-15, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [1, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [17, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [45, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, 29.5],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, 13],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, -3],
    rotation: [0, -Math.PI / 2, 0],
    scale: [95, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [17, 0.1, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [85, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [1, 0.1, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [85, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-15, 0.1, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [85, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-29, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [68, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-29, 0.1, -5],
    rotation: [0, -Math.PI / 1, 0],
    scale: [68, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [-29, 0.1, 15],
    rotation: [0, -Math.PI / 1, 0],
    scale: [68, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, -10],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, 3],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "gate",
    name: "Gate",
    model: "/assets/gate.glb",
    position: [26, 0.1, 15],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "tree1",
    name: "Tree1",
    model: "/assets/tree1.glb",
    position: [39, 0.1, -14],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.005,
  },
  {
    id: "tree2",
    name: "Tree2",
    model: "/assets/tree2.glb",
    position: [9, 0.1, -14],
    rotation: [0, -Math.PI / 1, 0],
    scale: 5,
  },
];
