// src/config/environmentConfig.js
export const environmentConfig = [
  {
    id: "zooenterence",
    name: "Zoo Entrance",
    model: "./assets/entrance.glb",
    position: [6, 0.5, 31.5],
    rotation: [0, 0, 0],
    scale: [3, 3, 3],
  },
 {
    id: "forest2",
    name: "Forest",
    model: "/assets/forest4.glb",
    position: [-1545, 0.1, -1080],
    rotation: [0, Math.PI/2, 0],
    scale: [30, 20, 20],
  },
 {
    id: "forest1",
    name: "Forest",
    model: "/assets/forest4.glb",
    position: [-1295, 0.1, -1080],
    rotation: [0, Math.PI/2, 0],
    scale: [30, 20, 20],
  },
  {
    id: "fountain",
    name: "Fountain",
    model: "./assets/fountain.glb",
    position: [5, -0.5, 2],
    rotation: [0, 0, 0],
    scale: 1.5,
  },
  // {
  //   id: "rhinobg",
  //   name: "Rhinobg",
  //   model: "./assets/rhinobg.glb",
  //   position: [33, 0.5, 12],
  //   rotation: [0, Math.PI, 0],
  //   scale: 0.5,
  // },
  {
    id: "barrier1",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [-17, 2.5, 31],
    rotation: [0, Math.PI, 0],
    scale: [5.3, 3, 2],
  },

  {
    id: "barrier2",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [30, 2.5, 31],
    rotation: [0, Math.PI, 0],
    scale: [5, 3, 2],
  },

  {
    id: "barrier3",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [-30, 2.5, 13],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier4",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [-30, 2.5, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier5",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [-12, 2.5, -40.5],
    rotation: [0, Math.PI, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier6",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [24, 2.5, -40.5],
    rotation: [0, Math.PI, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier7",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [42, 2.5, -25],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7, 3, 2],
  },

  {
    id: "barrier8",
    name: "Barrier",
    model: "./assets/barrier.glb",
    position: [42, 2.5, 12],
    rotation: [0, -Math.PI / 2, 0],
    scale: [7.5, 3, 2],
  },
  {
    id: "gate1",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-15, 0.1, 29.5],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate2",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-15, 0.1, 13],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate3",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-15, 0.1, -3],
    rotation: [0, -Math.PI / 2, 0],
    scale: [95, 60, 50],
  },
  {
    id: "gate4",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-15, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate5",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [1, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate6",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [17, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [45, 60, 50],
  },
  {
    id: "gate7",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [26, 0.1, 29.5],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate8",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [26, 0.1, 13],
    rotation: [0, -Math.PI / 2, 0],
    scale: [80, 60, 50],
  },
  {
    id: "gate9",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [26, 0.1, -3],
    rotation: [0, -Math.PI / 2, 0],
    scale: [95, 60, 50],
  },
  {
    id: "gate10",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [17, 0.1, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [85, 60, 50],
  },
  {
    id: "gate11",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [1, 0.1, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [85, 60, 50],
  },
  {
    id: "gate12",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-15, 0.1, -22],
    rotation: [0, -Math.PI / 2, 0],
    scale: [85, 60, 50],
  },
  {
    id: "gate13",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-29, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [68, 60, 50],
  },
  {
    id: "gate14",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-29, 0.1, -5],
    rotation: [0, -Math.PI / 1, 0],
    scale: [68, 60, 50],
  },
  {
    id: "gate15",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [-29, 0.1, 15],
    rotation: [0, -Math.PI / 1, 0],
    scale: [68, 60, 50],
  },
  {
    id: "gate16",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [26, 0.1, -22],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "gate17",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [26, 0.1, -10],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "gate18",
    name: "Gate",
    model: "./assets/gate.glb",
    position: [26, 0.1, 3],
    rotation: [0, -Math.PI / 1, 0],
    scale: [73, 60, 50],
  },
  {
    id: "cave65",
    name: "Cave",
    model: "./assets/cave.glb",
    position: [34, 0.1, 18],
    rotation: [0, -Math.PI / 11, 0],
    scale: [2, 3.5,1],
  },
  {
    id: "tree1",
    name: "Tree1",
    model: "./assets/tree1.glb",
    position: [-22, 0.1, -26],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.005,
  },
  {
    id: "tree25",
    name: "Tree2",
    model: "./assets/tree2.glb",
    position: [9, 0.1, -34],
    rotation: [0, -Math.PI / 1, 0],
    scale: 5,
  },
  {
    id: "tree3",
    name: "trunk",
    model: "./assets/tree3.glb",
    position: [9, 0.1, -34],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.01,
  },
  {
    id: "tree312",
    name: "Red tree",
    model: "./assets/tree4.glb",
    position: [-10, 0.1, -34],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.01,
  },
  
  {
    id: "tree52",
    name: "bamboo tree",
    model: "./assets/tree5.glb",
    position: [-20, 0.1, 12],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.04,
  },
  {
    id: "tree512",
    name: "bamboo tree",
    model: "./assets/tree5.glb",
    position: [-20, 0.1, -2],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.04,
  },
  {
    id: "tree588",
    name: "bamboo tree",
    model: "./assets/tree5.glb",
    position: [-28, 0.1, 8],
    rotation: [0, -Math.PI / 1, 0],
    scale: 0.02,
  },
  {
    id: "tree8",
    name: "tall tree",
    model: "./assets/tree8.glb",
    position: [-26, 0.1, -14],
    rotation: [0, -Math.PI / 1, 0],
    scale: 30,
  },
  {
    id: "tree7757",
    name: "neem tree",
    model: "./assets/tree7.glb",
    position: [1, -3, 10],
    rotation: [0, -Math.PI / 1, 0],
    scale: 1,
  },
  {
    id: "tree71",
    name: "bananatree",
    model: "./assets/bananatree.glb",
    position: [20, 0.1, -26],
    rotation: [0, -Math.PI / 1, 0],
    scale: 3,
  },
  // {
  //   id: "tree9",
  //   name: "bird tree",
  //   model: "./assets/tree9.glb",
  //   position: [9, 0.1, -14],
  //   rotation: [0, -Math.PI / 1, 0],
  //   scale: 100,
  // },
  {
    id: "water",
    name: "water",
    model: "./assets/water.glb",
    position: [-15, 1, -57],
    rotation: [0, -Math.PI / 2, 0],
    scale: [0.025, 0.02, 0.05],
  },
  {
    id: "water1",
    name: "water",
    model: "./assets/water.glb",
    position: [20, 1, -57],
    rotation: [0, -Math.PI / 2, 0],
    scale: [0.025, 0.02, 0.05],
  },
  {
    id: "water2",
    name: "water",
    model: "./assets/water.glb",
    position: [20, 0, -54],
    rotation: [0, -Math.PI / 2, 0],
    scale: [0.025, 0.02, 0.05],
  },
  {
    id: "water3",
    name: "water",
    model: "./assets/water.glb",
    position: [-15, 0, -54],
    rotation: [0, -Math.PI / 2, 0],
    scale: [0.025, 0.02, 0.05],
  },
  {
    id: "birdnest",
    name: "birdnest",
    model: "./assets/birdnest.glb",
    position: [-20, 1, -10],
    rotation: [0, -Math.PI / 2, 0],
    scale: 100,
  },
  {
    id: "snakenest",
    name: "snakenest",
    model: "./assets/snakenest.glb",
    position: [37, 0, -16],
    rotation: [0, -Math.PI / 2, 0],
    scale: [6,10,3],
  },
  {
    id: "igloo",
    name: "igloo",
    model: "./assets/igloo.glb",
    position: [30, 0, -2],
    rotation: [0, -Math.PI / 4, 0],
    scale: [1,1.5,1],
  },
  {
    id: "cave",
    name: "Cave",
    model: "./assets/cave.glb",
    position: [-24, 0.1, 26],
    rotation: [0, -Math.PI / 1, 0],
    scale: [1, 1,0.5],
  },
  {
    id: "cave1",
    name: "Cave",
    model: "./assets/cave.glb",
    position: [-24, 0.1, 26],
    rotation: [0, -Math.PI / 4, 0],
    scale: [1, 1,0.5],
  },
  {
    id: "tree211",
    name: "Tree2",
    model: "./assets/tree2.glb",
    position: [-23, 0.1, 20],
    rotation: [0, -Math.PI / 1, 0],
    scale: 5,
  },
];
