export const roadConfig = [
  {
    id: 1,
    texture: "/assets/road.png",
    position: [6, 0, 57.5],
    rotation: [-Math.PI / 2, 0, 0],
    size: [75, 50],
    repeat: [20, 20],
  },
  {
    id: 2,
    texture: "/assets/road.png",
    position: [-12, 0.1, 1],
    rotation: [-Math.PI / 2, 0, 1.55],
    size: [46, 4],
    repeat: [20, 5],
  },
  {
    id: 3,
    texture: "/assets/road.png",
    position: [7, 0.1, -20],
    rotation: [-Math.PI / 2, 0, 0],
    size: [38, 4],
    repeat: [20, 1],
  },
  {
    id: 4,
    texture: "/assets/road.png",
    position: [6, 0.1, 22],
    rotation: [-Math.PI / 2, 0, 0],
    size: [38, 4],
    repeat: [20, 1],
  },
  {
    id: 5,
    texture: "/assets/road.png",
    position: [23.5, 0.1, 1],
    rotation: [-Math.PI / 2, 0, 1.55],
    size: [46, 4],
    repeat: [20, 5],
  },
//   {
//     id: 6,
//     texture: "/assets/road.png",
//     position: [-12, 0.1, -8.5],
//     rotation: [-Math.PI / 2, 0, 1.55],
//     size: [38, 2],
//     repeat: [8, 4],
//   },
];
